#!/usr/bin/env bash
cd $(dirname $0)/..
set -e
set -x

rm -rf public/build
mkdir -p public/build

npm install

env NODE_ENV=production \
	./node_modules/.bin/browserify \
	--verbose \
	--transform [ babelify --presets [react es2015] ] \
	--entry src/app.js \
	--outfile public/build/bundle.js
