#!/usr/bin/env bash
cd $(dirname $0)/..
set -e
set -x

rm -rf public/build
mkdir -p public/build

test -d node_modules || npm install

env NODE_ENV=development \
	./node_modules/.bin/budo src/main.js:build/bundle.js \
	$* \
	--dir public \
	-- --verbose --debug --transform [ babelify --presets [react es2015] ]
